<?php
/**
 * Created by PhpStorm.
 * User: Wisdom Emenike
 * Date: 6/5/2020
 * Time: 12:21 PM
 */

namespace app\middleware;

use que\http\input\Input;
use que\security\Middleware;
use que\security\MiddlewareResponse;

class UserMiddleware extends Middleware
{

    public function handle(Input $input): MiddlewareResponse
    {
        if (!$input->user()) {
            $this->setAccess(false);
            $this->setTitle("Auth Error");
            $this->setResponse("Sorry, you must be logged in to access this route.");
            return $this;
        }
        return parent::handle($input); // TODO: Change the autogenerated stub
    }
}
