<?php


namespace que\middleware;


use que\common\validator\Track;
use que\http\input\Input;
use que\route\Route;
use que\security\CSRF;
use que\security\Middleware;
use que\security\MiddlewareResponse;

class AddTokensToHeaderResponse extends Middleware
{

    public function handle(Input $input): MiddlewareResponse
    {
        $route = Route::getCurrentRoute();

        if ($route->getType() === 'api' || $route->getType() === 'resource') {
            $input->getHeader()->set('X-Xsrf-Token', $csrf = CSRF::getInstance()->getToken());
            $input->getHeader()->set('X-Track-Token', Track::generateToken());
        }

        return parent::handle($input); // TODO: Change the autogenerated stub
    }

}