<?php


namespace que\middleware;


use que\http\input\Input;
use que\security\CSRF;
use que\security\Middleware;
use que\security\MiddlewareResponse;

class AddTokensToCookie extends Middleware
{

    public function handle(Input $input): MiddlewareResponse
    {
        $csrf = CSRF::getInstance();

        if (!$input->getCookie()->_isset('XSRF-TOKEN')) {
            $input->getCookie()->set("XSRF-TOKEN", $csrf->getToken(), $csrf->getExpiryTime());
        }

        return parent::handle($input); // TODO: Change the autogenerated stub
    }

}