<?php


namespace que\middleware;


use que\http\HTTP;
use que\http\input\Input;
use que\http\request\Request;
use que\route\Route;
use que\security\Middleware;
use que\security\MiddlewareResponse;

class CheckForAllowedRequestOrigin extends Middleware
{
    public function handle(Input $input): MiddlewareResponse
    {
        $route = Route::getCurrentRoute();
        $origins = $route->getAllowedOrigins();
        
        if (!in_array('*', $origins) && !in_array($origin = Request::getOrigin(), $origins)) {

            $message = "The origin [{$origin}] of this request is not supported for this route.";
            if (!LIVE) $message .= " Supported origins: " . (implode(", ", $route->getAllowedOrigins()) ?: "None") . ".";
            $this->setAccess(false);
            $this->setTitle("Unsupported Request Origin");
            $this->setResponse($message);
            $this->setResponseCode(HTTP::NOT_ACCEPTABLE);
            return $this;
        }
        return parent::handle($input); // TODO: Change the autogenerated stub
    }
}