<?php


namespace que\middleware;


use que\http\HTTP;
use que\http\input\Input;
use que\http\request\Request;
use que\route\Route;
use que\security\Middleware;
use que\security\MiddlewareResponse;

class CheckForAllowedRequestPort extends Middleware
{
    public function handle(Input $input): MiddlewareResponse
    {
        $route = Route::getCurrentRoute();

        $ports = $route->getAllowedPorts();

        if (!empty($ports) && !in_array($port = Request::getPort(), $ports)) {

            $this->setAccess(false);
            $this->setTitle("Unauthorized Request Port");
            $this->setResponse("You are not allowed to access this route on port [{$port}].");
            $this->setResponseCode(HTTP::UNAUTHORIZED);
            return $this;
        }
        return parent::handle($input); // TODO: Change the autogenerated stub
    }
}