<?php


namespace que\middleware;


use que\http\HTTP;
use que\http\input\Input;
use que\route\Route;
use que\security\Middleware;
use que\security\MiddlewareResponse;

class CheckForMaintenanceMode extends Middleware
{
    public function handle(Input $input): MiddlewareResponse
    {
        if (Route::getCurrentRoute()->isUnderMaintenance()) {
            $this->setAccess(false);
            $this->setTitle("Maintenance Mode");
            $this->setResponse("This route is currently under maintenance, please try again later.");
            $this->setResponseCode(HTTP::MAINTENANCE);
            return $this;
        }
        return parent::handle($input); // TODO: Change the autogenerated stub
    }
}