<?php


namespace que\middleware;


use que\http\HTTP;
use que\http\input\Input;
use que\http\request\Request;
use que\route\Route;
use que\security\Middleware;
use que\security\MiddlewareResponse;

class CheckForAllowedRequestIP extends Middleware
{
    public function handle(Input $input): MiddlewareResponse
    {
        $route = Route::getCurrentRoute();

        $ips = $route->getAllowedIPs();

        if (!empty($ips) && !in_array($ip = Request::getClientIp(), $ips)) {

            $this->setAccess(false);
            $this->setTitle("Unauthorized Request IP");
            $this->setResponse("Your IP address [{$ip}] is not allowed to access this route.");
            $this->setResponseCode(HTTP::UNAUTHORIZED);
            return $this;
        }
        return parent::handle($input); // TODO: Change the autogenerated stub
    }
}